### ISSUE TITLE
Is this project completed? or still under development?

### ISSUE THREAD

**Issue by rider8581** [CubanJaco/Wisper#1]
Is this project completed? or still under development?

**Comment by CubanJaco** [comment]
The main functionality is implemented (make a phone hard reset just by pressing a single panic button) but i had no time to finish the project.
If you want to test it just need to uncomment line 27 in ./Wisper/app/src/main/java/cu/jaco/wisper/utils/Utils.kt file (`mDPM.wipeData(flags)`) which is commented by security while testing.

All contributions are wellcome

**Comment by rider8581** [comment]
After 30 seconds, it is just showing the following screen.
![image](https://user-images.githubusercontent.com/52605718/135483679-436902c6-1d8f-4c0a-8c7e-a5126b8345cd.png)
Does it mean the factory reset finishes?
I enabled this line.
![image](https://user-images.githubusercontent.com/52605718/135484319-0128a495-65ec-4b05-a2ff-1acdd5ba7e37.png)

**Comment by CubanJaco** [comment]
By some reason I don't know, Factory Reset doesn't work in virtual machine, but it work in real devices. I had tested just in my phone and worked fine. The count down is just for security, you can cancel before it comes to 0 (with swipe in the bottom bar), after count down finished your phone should restart and make a factory reset. Also you have a way to make a Factory Reset without the countdown pushing 3 times the red button. Please, take in count this is just an idea I had, but obviously isn't finished and just tested a few times in my own phone.
