### ISSUE TITLE
What is missing?

### ISSUE THREAD

**Issue by rider8581** [CubanJaco/Wisper#2]
Would you let me know what is missing in this project?

**Comment by CubanJaco** [comment]
The main idea consist in an app that you can use in case of kidnap, steal or just for remove all data in your device by security in a few seconds. 
Right now you have a single view with a red button. Thirty seconds after you pressed this button, your phone should restart and make a factory reset to delete all your device data. This proccess can be canceled with a single swipe right at the bottom bar. Also you have the option to skip this count down by pushing 3 times the red button and directly make a factory reset.
This is what should work right now in my app. I have been thinking about a screen widget and shortcuts to make the process faster and a few configurations to remove or not external storage data.
